# Services
services:

  # MariaDB Service
  db:
    # imagen de mariadb
    image: mariadb:11.0.2-jammy
    # nombre del contenedor
    container_name: dev-mariadb
    # variables de entorno
    environment:
      # contraseña de root
      MYSQL_ROOT_PASSWORD: root
      # nombre de la BBDD
      MYSQL_DATABASE: test
      # usuario de acceso a la BBDD
      MYSQL_USER: test
      # contraseña de acceso a ls BBD
      MYSQL_PASSWORD: test
    # Volumen con los datos de la BBDD
    volumes:
      - ./db-data:/var/lib/mysql

  # phpMyAdmin Service
  phpmyadmin:
    # imagen de Phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    # nombre del contenedor
    container_name: dev-phpmyadmin
    # accedemos al puerto 8081 local (host) (izquierda)
    # aunque el puerto del contenedor es el 80 (derecha)
    # URL: http://localhost:8081
    ports:
      - 8081:80
    # Variables de entorno
    environment:
      # definición del nombre del host(contenedor) de la BBDD
      PMA_HOST: db
    # Se arranca después del contenedor de la BBDD
    depends_on:
      - db
  # PHP Service
  php:
    # pilla el fichero Dockerfile para crear la imagen
    build:
      context: .
      dockerfile: Dockerfile.drupal
    # nombre del contenedor PHP
    container_name: dev-php
    env_file:
      - .env
    # definición del volumen con el código PHP
    volumes:
      - './src:/var/www/html'
      - './conf/php/php.ini:/usr/local/etc/php/php.ini'
    # dependencia del contenedor mariadb
    depends_on:
      - db

  # Nginx Service
  nginx:
    # pilla la última imagen de nginx
    image: nginx:latest
    # nombre del contenedor
    container_name: dev-nginx
    # user: "1000:1000"
    # ofrece en el puerto 81 en el host (izquierda)
    # y en este caso el 81 del contenedor (derecha)
    # url: http://localhost:81/ ó http://localhost
    ports:
      - 81:80
    #links:
    #  - 'php'

    volumes:
      # Define el volumen con el código de PHP
      - './src:/var/www/html'
      - './logs/nginx:/var/log/nginx'
      # define el volumen con los ficheros de configuración
      # fichero nginx.conf (host) -> /etc/nginx/conf.d/nginx.conf (contenedor)
      - './conf/nginx-drupal:/etc/nginx/conf.d'
    # depende del servicio de PHP
    depends_on:
      - php
  # Varnish Container
  varnish:
    image: varnish:fresh
    depends_on:
      - nginx
    container_name: dev-varnish
    restart: always
    ports:
      - 80:80
    volumes:
      # if you want to check the logs
      - ./logs/varnish:/var/log/
      - ./conf/varnish-drupal/varnish.vcl:/etc/varnish/default.vcl:ro
    environment:
      BACKENDS: "nginx"
      BACKENDS_PORT: 80
      BACKENDS_PROBE_ENABLED: "false"
    logging:
      options:
        max-size: 10m



